### ISSUE TITLE
on load once

### ISSUE THREAD

**Issue by natxopedreira** [armadillu/ofxProgressiveTextureLoad#2] opened 2015-04-26 14:12 UTC
Hi
I want to use this nice addon but seems like with the example i can not load another image after doing on setup, loading one image on setup Works great but when i want to call again loadTexture it doesnt work, im tracing the status and it gets stuck on ALLOC_TEXTURE

thaanks

**Comment by armadillu** [comment] 2015-04-26 14:26
Are you on Windows + ATI card? It is known to immediatelly crash on this configuration; I haven't had to figure out what's wrong with it in this platform config.

**Comment by armadillu** [comment] 2015-04-26 14:27
let me test, I made some changes a while ago and haven't updated the example...

**Comment by armadillu** [comment] 2015-04-26 14:42
Yep, I can confirm this. The issue is that I never use ofxProgressiveTextureLoad directly, always in conjunction with the ProgressiveTextureLoadQueue... And I made some changes that break it. The easy solution for now is to create a new texture loader object every time you want to load a texture; but I recommend you use the ProgressiveTextureLoadQueue.

**Comment by natxopedreira** [comment] 2015-04-26 15:15
Yep im on windows, intel 4000 graphic card.

I will look at the queue option

Thanks!

**Comment by armadillu** [comment] 2015-04-26 15:20
It's fixed now; both examples updated too.

**Closed as completed by armadillu** 2015-04-26 15:20 UTC
